version: '3'
services:
    db:
        volumes:
            - "./logs/postgres:/var/log/postgresql"
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile-production
        environment:
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_PROD}
        volumes:
            - "./logs/app:/tmp/logs/app"
            - "./logs/gunicorn:/tmp/logs/gunicorn"
            - "./backend/media:/media"
        depends_on:
            - db
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - backend
        volumes: 
            - "./backend/media:/media"
            - "./logs/nginx:/tmp/logs"
        ports:
            - "80:80"
            - "443:443"

