version: '3'
services:
    db:
        volumes:
            - "./logs/postgres:/var/log/postgresql"
    frontend:
        container_name: frontend
        image: node:5.10
        working_dir: /frontend
        command: npm run-script start
        volumes:
            - ./frontend:/frontend
        ports:
            - "3000:3000"
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile-production
        environment:
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_PROD}
        volumes:
            - "./logs/app:/tmp/logs/app"
            - "./logs/gunicorn:/tmp/logs/gunicorn"
            - "./backend/media:/media"
        depends_on:
            - db
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - backend
            - frontend
        volumes:
            - "./backend/media:/media"
            - "./logs/nginx:/tmp/logs"
        ports:
            - "80:80"
            - "443:443"
