version: '3'
volumes:
    data:
services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: backend
            POSTRES_PASSWORD: backend
        volumes:
            - data:/var/lib/postgresql/data