version: '3'
volumes:
    data:
services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - data:/var/lib/postgresql/data
